### ISSUE TITLE
Oracle 12c SQL_FULL_PLAN_HASH_VALUE error for oracle.session_io_log

### ISSUE THREAD

**Issue by darrynv** [smartmarmot/DBforBIX#36]
[2017-06-02 12:58:21] [ERROR] [zabbixserver:10051/zabbixdbforbixproxy/eppstud.dbs.dev.det.nsw.edu.au/eppstud/oracle.discovery.DB4bix.config[instanceid,{$DSN}][getItemData(SimpleItem.java:99)]]: Cannot get data for item:
oracle.session_io_log
Query:
select LISTAGG(SUBSTR(sessions_tab,1,395),chr(10)) WITHIN GROUP(ORDER BY PCT desc) sessions from ( select INST_ID||': '||'PCT[R/W/T,MB/s]='||PCT||'['||SESSION_IO_R_MBps||'/'||SESSION_IO_W_MBps||'/'||TOTAL_IO_MBps||'];SQL_(ID/FULL_PLAN_HV)='||SQL_ID||'/'||sql_full_plan_hash_value||';SID='||sid||'#'||SERIAL#||';(SCH/USER)NAME='||SCHEMANAME||'/'||USERNAME||';STATUS='||STATUS||';TYPE='||TYPE||';OSUSER='||OSUSER||';PROGRAM='||REGEXP_REPLACE(PROGRAM,'@.*$','')||'@'||MACHINE||';PROCESS='||PROCESS||';'||DESCRIPTION sessions_tab, PCT from ( select b.inst_id,b.sid,b.SERIAL#,b.SCHEMANAME,b.OSUSER,b.USERNAME,b.STATUS,b.SQL_ID,b.PROCESS,b.PROGRAM,b.MACHINE,b.TYPE, round(100*(sio.SESSION_IO_R+sio.SESSION_IO_W)/fio.TOTAL_IO,2) PCT,round(sio.SESSION_IO_R,2) SESSION_IO_R_MBps, round(sio.SESSION_IO_W,2) SESSION_IO_W_MBps,round(fio.TOTAL_IO, 2) TOTAL_IO_MBps,p.DESCRIPTION, sio.sql_full_plan_hash_value from gv$session b, gv$bgprocess p, ( select inst_id, sum(((DELTA_READ_IO_BYTES/1024/1024)+(DELTA_WRITE_IO_BYTES/1024/1024))/(DELTA_TIME/1000000))/600 total_io from GV$ACTIVE_SESSION_HISTORY where sample_time > sysdate-10/24/60 group by inst_id ) fio,( select inst_id, session_id,sum((DELTA_READ_IO_BYTES/1024/1024)/(DELTA_TIME/1000000))/600 session_io_r, sum((DELTA_WRITE_IO_BYTES/1024/1024)/(DELTA_TIME/1000000))/600 session_io_w, sql_full_plan_hash_value from GV$ACTIVE_SESSION_HISTORY where sample_time > sysdate-10/24/60 group by inst_id, session_id, sql_full_plan_hash_value ) sio where p.paddr(+) = b.paddr and p.inst_id(+)=b.inst_id and sio.session_id = b.sid and sio.inst_id=b.inst_id and fio.inst_id=b.inst_id order by PCT desc nulls last ) where rownum < 11)
**java.sql.SQLSyntaxErrorException: ORA-00904: "SQL_FULL_PLAN_HASH_VALUE": invalid identifier**

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1104)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at com.smartmarmot.dbforbix.scheduler.SimpleItem.getItemData(SimpleItem.java:55)
	at com.smartmarmot.dbforbix.scheduler.Scheduler.run(Scheduler.java:97)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by kjlt** [comment]
Looks like it's 12c featured SQL. It doesn't work on 11g.

**Comment by vagabondan** [comment]
@KJlt77 Yes, this should be corrected for 11g on SQL_PLAN_HASH_VALUE
