### ISSUE TITLE
Problem during install or 1st run

### ISSUE THREAD

**Issue by rafaelbs2** [smartmarmot/DBforBIX#60]
Hi, I'm trying to use DbforBix to monitor a Mysql DB. I already use it to monitor oracle (Orabbix version).

I'm using openjdk-11.

Tried to run version 3.0 and 2.4. Had the same issue with both, when executing the command 
java -jar dbforbix.jar -b `pwd` -a start

2018-09-24 23:44:47] [DEBUG] [main[readFileConfig(Config.java:594)]]: Parsing config file: /opt/dbforbix/conf/config.properties
[2018-09-24 23:44:47] [FATAL] [main[main(DBforBix.java:229)]]: DBforBix crashed!
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
	at com.smartmarmot.dbforbix.config.Config.calculateFileConfigHash(Config.java:580)
	at com.smartmarmot.dbforbix.config.Config.readFileConfig(Config.java:595)
	at com.smartmarmot.dbforbix.DBforBix.reinit(DBforBix.java:66)
	at com.smartmarmot.dbforbix.DBforBix.main(DBforBix.java:173)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.HexBinaryAdapter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
[2018-09-24 23:44:47] [DEBUG] [main[readFileConfig(Config.java:594)]]: Parsing config file: /opt/dbforbix/conf/config.properties
[2018-09-24 23:44:47] [FATAL] [main[main(DBforBix.java:229)]]: DBforBix crashed!
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
	at com.smartmarmot.dbforbix.config.Config.calculateFileConfigHash(Config.java:580)
	at com.smartmarmot.dbforbix.config.Config.readFileConfig(Config.java:595)
	at com.smartmarmot.dbforbix.DBforBix.reinit(DBforBix.java:66)
	at com.smartmarmot.dbforbix.DBforBix.main(DBforBix.java:173)

am I doing something wrong or is it really some kind of issue?

Regards,
Rafael

**Comment by rafaelbs2** [comment]
Thanks for such a quick answer Jedd. Good to know that you had success with oracle. Which version of dbforbix are you using?

Here goes my config.properties:

```
#frequency of update config in seconds
DBforBIX.UpdateConfigTimeout=120

#MaxThreadNumber should be >= than the number of your databases
MaxThreadNumber=1

#
#### Configuration of Connection pool ###
#
## Maximum number of active connection inside pool
#
## Login Timeout
Pool.LoginTimeOut=15

#
### Zabbix servers ###
# A list of Zabbix servers, change the name after first dot to add more
# Zabbix Server
ZabbixServer.Zabbix1.Address=127.0.0.1
# Zabbix server port (trapper port)
ZabbixServer.Zabbix1.Port=10051
# Name of Zabbix proxy (you should create this name on your Zabbix Web Interface)
# It will be used to get hosts and items configurations
ZabbixServer.Zabbix1.ProxyName=DBforBIX
# Item key suffix to find its configuration on Zabbix Server
ZabbixServer.Zabbix1.ConfigSuffix=DBforBIX.config
# List of comma separated databases
# This names also should be defined in your Template/Host macros {$DSN} in Zabbix Web Interface
# See zabbix templates attached for further details
ZabbixServer.Zabbix1.DBList=MYSQLDB1
###
#

### Database servers ###

###MySQL Server
#define here your connection string for each database
#on the following example we are treating MySQL
DB.MYSQLDB1.Url=jdbc:mysql://localhost:3306/mydatabase
DB.MYSQLDB1.Instance=mydatabase
DB.MYSQLDB1.User=user
DB.MYSQLDB1.Password=password
DB.MYSQLDB1.Type=mysql
DB.MYSQLDB1.MaxActive=10
DB.MYSQLDB1.MaxWaitMillis=10000
DB.MYSQLDB1.QueryTimeout=15
DB.MYSQLDB1.MaxIdle=1
```

**Comment by jedd** [comment]
Hehe .. don't get too optimistic -- I mostly asked you to post that so someone smarter than me can look at it and help more easily.

I've not used DBforBIX for anything other than Oracle (11 & 12).  I'm using the latest pull from the repo.

I have tried with PostgreSQL 10, but had no luck at all -- Postgres makes lots of changes between major releases and it's been a while since DBforBIX got some updates.   I haven't tried it with My/MariaSQL.

Two things I'd suggest trying.

Comment-out the MySQL paragraph entirely and see if the jar file will launch.   Note that you can change that first time-out to something small - 20s say - and then once you get it running, you can tail -f your dbforbix.log file in one terminal, while slowly adding out the stanza again in another.  I've done something similar while experimenting with config syntax - messy but effective.

And/or try running it with the same config but an earlier version of Java (I'm using OpenJRE too) -- perhaps try v1.8.

**Comment by rafaelbs2** [comment]
Hi,

Thanks again Jedd!

I tried using Java 1.8 and had a different error:

```
root@zbx00k:/opt/dbforbix# java -jar dbforbix.jar -b `pwd` -a start 
[2018-09-26 09:55:46] [DEBUG] [main[readFileConfig(Config.java:594)]]: Parsing config file: /opt/dbforbix/conf/config.properties
[2018-09-26 09:55:46] [INFO ] [main[reinit(DBforBix.java:99)]]: ### executing DBforBix Version 2.4-beta: Wed Sep 26 09:55:46 BRT 2018
[2018-09-26 09:55:46] [INFO ] [main[reinit(DBforBix.java:100)]]: using config file /opt/dbforbix/conf/config.properties
[2018-09-26 09:55:46] [DEBUG] [main[reinit(DBforBix.java:101)]]: Config:

BaseDir:	/opt/dbforbix
-- Zabbix:	127.0.0.1:10051
-- Database:	DSN:MYSQLDB1,	type:MYSQL,	URL:jdbc:mysql://localhost:3306/mydatabase,	Instance:mydatabase

[2018-09-26 09:55:46] [FATAL] [main[main(DBforBix.java:229)]]: DBforBix crashed!
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
	at com.smartmarmot.dbforbix.config.Config.getItemConfigFromZabbix(Config.java:1208)
	at com.smartmarmot.dbforbix.DBforBix.reinit(DBforBix.java:104)
	at com.smartmarmot.dbforbix.DBforBix.main(DBforBix.java:173)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

I also commented the MySQL paragraph, and the error was kind of the same:

```
root@zbx00k:/opt/dbforbix# java -jar dbforbix.jar -b `pwd` -a start 
[2018-09-26 10:00:34] [DEBUG] [main[readFileConfig(Config.java:594)]]: Parsing config file: /opt/dbforbix/conf/config.properties
[2018-09-26 10:00:34] [INFO ] [main[reinit(DBforBix.java:99)]]: ### executing DBforBix Version 2.4-beta: Wed Sep 26 10:00:34 BRT 2018
[2018-09-26 10:00:34] [INFO ] [main[reinit(DBforBix.java:100)]]: using config file /opt/dbforbix/conf/config.properties
[2018-09-26 10:00:34] [DEBUG] [main[reinit(DBforBix.java:101)]]: Config:

BaseDir:	/opt/dbforbix
-- Zabbix:	127.0.0.1:10051

[2018-09-26 10:00:34] [FATAL] [main[main(DBforBix.java:229)]]: DBforBix crashed!
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSON
	at com.smartmarmot.dbforbix.config.Config.getItemConfigFromZabbix(Config.java:1208)
	at com.smartmarmot.dbforbix.DBforBix.reinit(DBforBix.java:104)
	at com.smartmarmot.dbforbix.DBforBix.main(DBforBix.java:173)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSON
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

Any other idea?

Thanks!

**Comment by rafaelbs2** [comment]
The post above was with the 2.4 version... Finally got it running with version 3.0 and Java 1.8.

Thanks!!!
